import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.scss";

const lexendDecaRegular = localFont({
  src: "./fonts/LexendDeca-Regular.ttf",
  variable: "--font-lexend-regular",
  weight: "400",
});
const lexendDecaSemiBold = localFont({
  src: "./fonts/LexendDeca-SemiBold.ttf",
  variable: "--font-lexend-semibold",
  weight: "600",
});

export const metadata: Metadata = {
  title: "aiezq | портфолио",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexendDecaRegular.variable} ${lexendDecaSemiBold.variable}`}>
        {children}
      </body>
    </html>
  );
}
